{% set name = "ndindex" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e35fe1babe2d11c0b7af55b93b64f9c2725ea19a5d81c973fb8a2db5fbf3902e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - sympy

test:
  imports:
    - ndindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://quansight.github.io/ndindex/
  summary: A Python library for manipulating indices of ndarrays.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Quansight/ndindex

extra:
  recipe-maintainers:
    - asmeurer
