{% set name = "ndindex" %}
{% set version = "1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf9bd0b76eeada1c8275e04091f8291869ed2b373b7af48e56faf7579fd2efd2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ndindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://quansight.github.io/ndindex/
  summary: A Python library for manipulating indices of ndarrays.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Quansight/ndindex

extra:
  recipe-maintainers:
    - asmeurer
